language: android
jdk: oraclejdk8
dist: trusty
group: edge
android:
  components:
    - tools
    - platform-tools
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - build-tools-29.0.3
    - android-29
before_install:
  - pip install --user codecov
script:
  - ./gradlew jacocoTestReport
  - ./gradlew connectedCheck
  - bash <(curl -s https://codecov.io/bash) 
after_success:
    - codecov -t 43491081-a94f-4ce6-8688-5724d791ae79