language: android
jdk: oraclejdk8
android:
  components:
    # Update Android SDK Tools
    - tools

    - build-tools-29.0.3
    - android-29

    # Support library
    - extra-android-support
    - extra-android-m2repository
    - extra-google-google_play_services
before_install:
  - echo no | android create avd --force -n test -t android-22 --abi armeabi-v7a -c 100M
  - emulator -avd test -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &
after_success:
  - bash <(curl -s https://codecov.io/bash) -t 43491081-a94f-4ce6-8688-5724d791ae79