language: android
dist: trusty
android:
  components:
    - tools
    - platform-tools
    - build-tools-26.0.2
    - android-26
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - sys-img-x86-android-26
before_install:
  - chmod +x gradlew
after_success:
  - bash <(curl -s https://codecov.io/bash) -t 43491081-a94f-4ce6-8688-5724d791ae79