language: android
jdk: oraclejdk8
dist: trusty
env:
  global: # Updating variables becomes easy
    - ANDROID_BUILD_TOOLS_VERSION=26.0.2
    - ANDROID_ABI=arm64-v8a
    - ANDROID_TAG=google_apis # Google API
    - ANDROID_API_LEVEL=26
    - EMULATOR_API_LEVEL=25
    - ADB_INSTALL_TIMEOUT=8 # 8 minutes
android:
  components:
    - tools
    - platform-tools
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION
    - android-$ANDROID_API_LEVEL
    - android-$EMULATOR_API_LEVEL
    - sys-img-$ANDROID_ABI-$ANDROID_TAG-$EMULATOR_API_LEVEL
before_script:
  - android list targets
  - echo no | android create avd --force -n buildtest -t "android-"$EMULATOR_API_LEVEL --abi $ANDROID_ABI --tag $ANDROID_TAG
  - emulator -list-avds
  - emulator -avd buildtest -no-window &
  - android-wait-for-emulator
  - adb devices
  - adb shell input keyevent 82 &
before_install:
  - pip install --user codecov
script:
  - ./gradlew build jacocoTestReport assembleAndroidTest
  - ./gradlew connectedCheck
  - bash <(curl -s https://codecov.io/bash) 
after_success:
    - codecov -t 43491081-a94f-4ce6-8688-5724d791ae79